/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "gpjson/cuda/cuda.hpp"
#include "gpjson/cuda/error.hpp"
#include "utils/utils.hpp"

#include <gtest/gtest.h>

#include <utility>
#include <vector>

TEST(DeviceArrayTest, DefaultAndZeroByteArraysAreEmpty) {
  gpjson::cuda::DeviceArray empty;
  EXPECT_TRUE(empty.empty());
  EXPECT_EQ(empty.data(), nullptr);
  EXPECT_EQ(empty.size_bytes(), 0);

  gpjson::cuda::DeviceArray zero(0);
  EXPECT_TRUE(zero.empty());
  EXPECT_EQ(zero.data(), nullptr);
  EXPECT_EQ(zero.size_bytes(), 0);

  zero.copy_from_host(nullptr, 0);
  zero.copy_to_host(nullptr, 0);
  zero.memset(0);
}

TEST(DeviceArrayTest, AllocationReportsRequestedByteSize) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::cuda::DeviceArray array(16);
  EXPECT_FALSE(array.empty());
  EXPECT_NE(array.data(), nullptr);
  EXPECT_EQ(array.size_bytes(), 16);
}

TEST(DeviceArrayTest, CopyRoundTripPreservesData) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  std::vector<int> input{1, 2, 3, 4};
  std::vector<int> output(input.size(), 0);
  gpjson::cuda::DeviceArray array(input.size() * sizeof(int));

  array.copy_from_host(input.data(), input.size() * sizeof(int));
  array.copy_to_host(output.data(), output.size() * sizeof(int));

  EXPECT_EQ(output, input);
}

TEST(DeviceArrayTest, MemsetClearsDeviceArray) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  std::vector<int> input{1, 2, 3, 4};
  std::vector<int> output(input.size(), -1);
  gpjson::cuda::DeviceArray array(input.size() * sizeof(int));

  array.copy_from_host(input.data(), input.size() * sizeof(int));
  array.memset(0);
  array.copy_to_host(output.data(), output.size() * sizeof(int));

  EXPECT_EQ(output, std::vector<int>(input.size(), 0));
}

TEST(DeviceArrayTest, MoveConstructorTransfersOwnership) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::cuda::DeviceArray source(16);
  void *source_ptr = source.data();

  gpjson::cuda::DeviceArray moved(std::move(source));

  EXPECT_TRUE(source.empty());
  EXPECT_EQ(source.data(), nullptr);
  EXPECT_EQ(source.size_bytes(), 0);
  EXPECT_EQ(moved.data(), source_ptr);
  EXPECT_EQ(moved.size_bytes(), 16);
}

TEST(DeviceArrayTest, MoveAssignmentReplacesCurrentAllocation) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::cuda::DeviceArray source(16);
  void *source_ptr = source.data();
  gpjson::cuda::DeviceArray target(8);

  target = std::move(source);

  EXPECT_TRUE(source.empty());
  EXPECT_EQ(source.data(), nullptr);
  EXPECT_EQ(source.size_bytes(), 0);
  EXPECT_EQ(target.data(), source_ptr);
  EXPECT_EQ(target.size_bytes(), 16);
}

TEST(DeviceArrayTest, OversizedCopyFromHostThrows) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::cuda::DeviceArray array(4);
  int value = 0;

  EXPECT_THROW(array.copy_from_host(&value, sizeof(value) + 1),
               gpjson::error::cuda::CudaError);
}

TEST(DeviceArrayTest, OversizedCopyToHostThrows) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::cuda::DeviceArray array(4);
  int value = 0;

  EXPECT_THROW(array.copy_to_host(&value, sizeof(value) + 1),
               gpjson::error::cuda::CudaError);
}
