/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#pragma once

#include "gpjson/cuda/cuda.hpp"

#define private public
#include "gpjson/file/file.hpp"
#undef private

#include "gpjson/index/index.hpp"
#include "gpjson/index/index_builder.hpp"

#include <gtest/gtest.h>

#include <array>
#include <cuda_runtime_api.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace gpjson::test::index {

inline constexpr int kMaxDepth = 8;
inline constexpr std::array<gpjson::index::IndexBuilderType, 4>
    kIndexBuilderTypes{
        gpjson::index::IndexBuilderType::UNCOMBINED,
        gpjson::index::IndexBuilderType::COMBINED,
        gpjson::index::IndexBuilderType::FUSED,
        gpjson::index::IndexBuilderType::SHAREMEM,
    };

inline long word_from_bits(uint64_t bits) {
  long word = 0;
  static_assert(sizeof(word) == sizeof(bits));
  std::memcpy(&word, &bits, sizeof(word));
  return word;
}

inline uint64_t bit_for(size_t offset) { return uint64_t{1} << (offset % 64); }

inline size_t level_size_for(size_t file_size) {
  return (file_size + 64 - 1) / 64;
}

/* Create a FilePartition from a cpp string */
class StaticPartition {
public:
  explicit StaticPartition(std::string data) : data_(std::move(data)) {
    view_.partition_id_ = 0;
    view_.global_start_offset_ = 0;
    view_.global_end_offset_ = data_.size();
    view_.host_data_ = reinterpret_cast<const std::byte *>(data_.data());
  }

  file::FilePartition &view() { return view_; }

  const file::FilePartition &view() const { return view_; }

  void load_to_device() { view_.load_to_device(); }

  const std::string &data() const { return data_; }

private:
  std::string data_;
  file::FilePartition view_;
};

inline std::string ld_json_fixture() {
  return std::string{
      "{\"id\":1,\"name\":\"Ada\",\"tags\":[\"gpu\",\"json\"],\"active\":true}"
      "\n"
      "{\"id\":2,\"name\":\"Bob \\\"The Builder\\\"\","
      "\"note\":\"literal { braces } and [brackets] stay strings\"}"
      "\n"
      "{\"id\":3,\"nested\":{\"arr\":[1,{\"x\":\"y,z\"}],\"empty\":{}},"
      "\"path\":\"C:\\\\tmp\\\\file\"}"};
}

inline std::vector<long> copy_index_words(const gpjson::index::Index &index) {
  std::vector<long> words(index.size_bytes() / sizeof(long), 0);
  if (index.size_bytes() > 0) {
    cuda::check(cudaMemcpy(words.data(), index.data(), index.size_bytes(),
                           cudaMemcpyDeviceToHost),
                "cudaMemcpy index to host");
  }
  return words;
}

inline const char *
index_builder_type_name(gpjson::index::IndexBuilderType builder_type) {
  switch (builder_type) {
  case gpjson::index::IndexBuilderType::UNCOMBINED:
    return "UNCOMBINED";
  case gpjson::index::IndexBuilderType::COMBINED:
    return "COMBINED";
  case gpjson::index::IndexBuilderType::FUSED:
    return "FUSED";
  case gpjson::index::IndexBuilderType::SHAREMEM:
    return "SHAREMEM";
  }

  throw std::invalid_argument("Unknown index builder type.");
}

inline std::string index_builder_type_test_name(
    const ::testing::TestParamInfo<gpjson::index::IndexBuilderType> &info) {
  return index_builder_type_name(info.param);
}

inline std::unique_ptr<gpjson::index::IndexBuilder>
make_index_builder(gpjson::index::IndexBuilderType builder_type,
                   const gpjson::file::FileReader &file_reader) {
  switch (builder_type) {
  case gpjson::index::IndexBuilderType::UNCOMBINED:
    return std::make_unique<gpjson::index::UncombinedIndexBuilder>(file_reader);
  case gpjson::index::IndexBuilderType::COMBINED:
    return std::make_unique<gpjson::index::CombinedIndexBuilder>(file_reader);
  case gpjson::index::IndexBuilderType::FUSED:
    return std::make_unique<gpjson::index::FusedIndexBuilder>(file_reader);
  case gpjson::index::IndexBuilderType::SHAREMEM:
    return std::make_unique<gpjson::index::SharememIndexBuilder>(file_reader);
  }

  throw std::invalid_argument("Unknown index builder type.");
}

inline gpjson::index::IndexBuilderOptions
small_builder_options(gpjson::index::IndexBuilderType builder_type =
                          gpjson::index::IndexBuilderType::UNCOMBINED) {
  return gpjson::index::IndexBuilderOptions{
      builder_type, 0, 1, 64, 1, 64,
  };
}

} // namespace gpjson::test::index
