/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "index/index_test_utils.hpp"
#include "utils/utils.hpp"

#include "gpjson/cuda/cuda.hpp"
#include "gpjson/file/file_reader.hpp"
#include "gpjson/index/index_builder.hpp"

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace {

class LeveledBitmapIndexBuilderTest
    : public ::testing::TestWithParam<gpjson::index::IndexBuilderType> {};

bool is_escaped_quote(const std::string &data, size_t quote_offset) {
  size_t slash_count = 0;
  for (size_t i = quote_offset; i > 0 && data[i - 1] == '\\'; --i) {
    ++slash_count;
  }
  return slash_count % 2 == 1;
}

std::vector<uint64_t> expected_string_bits(const std::string &data) {
  std::vector<uint64_t> words(gpjson::test::index::level_size_for(data.size()),
                              0);
  bool in_string = false;

  for (size_t i = 0; i < data.size(); ++i) {
    if (data[i] == '"' && !is_escaped_quote(data, i)) {
      if (!in_string) {
        words[i / 64] |= gpjson::test::index::bit_for(i);
        in_string = true;
      } else {
        in_string = false;
      }
    } else if (in_string) {
      words[i / 64] |= gpjson::test::index::bit_for(i);
    }
  }

  return words;
}

std::vector<long> expected_leveled_bitmap_index(const std::string &data,
                                                int num_levels) {
  const size_t level_size = gpjson::test::index::level_size_for(data.size());
  const std::vector<uint64_t> string_bits = expected_string_bits(data);
  std::vector<uint64_t> levels(level_size * num_levels, 0);
  int level = -1;

  for (size_t i = 0; i < data.size(); ++i) {
    if ((string_bits[i / 64] & gpjson::test::index::bit_for(i)) != 0) {
      continue;
    }

    const char value = data[i];
    if (value == '{' || value == '[') {
      ++level;
      if (level >= 0 && level < num_levels) {
        levels[level_size * level + i / 64] |= gpjson::test::index::bit_for(i);
      }
    } else if (value == '}' || value == ']') {
      if (level >= 0 && level < num_levels) {
        levels[level_size * level + i / 64] |= gpjson::test::index::bit_for(i);
      }
      --level;
    } else if (value == ':' || value == ',') {
      if (level >= 0 && level < num_levels) {
        levels[level_size * level + i / 64] |= gpjson::test::index::bit_for(i);
      }
    }
  }

  std::vector<long> expected;
  for (uint64_t word : levels) {
    expected.push_back(gpjson::test::index::word_from_bits(word));
  }
  return expected;
}

TEST_P(LeveledBitmapIndexBuilderTest, BuildsLeveledBitmapIndex) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::test::index::StaticPartition partition(
      gpjson::test::index::ld_json_fixture());
  partition.load_to_device();
  gpjson::file::CopiedFileReader file_reader{"in-memory.ldjson"};
  const gpjson::index::IndexBuilderType builder_type = GetParam();
  auto builder =
      gpjson::test::index::make_index_builder(builder_type, file_reader);

  gpjson::index::BuiltIndices indices =
      builder->build(partition.view(), gpjson::test::index::kMaxDepth,
                     gpjson::test::index::small_builder_options(builder_type));
  gpjson::cuda::synchronize();

  const std::vector<long> expected = expected_leveled_bitmap_index(
      partition.data(), gpjson::test::index::kMaxDepth);
  const gpjson::index::LeveledBitmapIndex &leveled_bitmap_index =
      indices.get_leveled_bitmap_index();

  EXPECT_EQ(leveled_bitmap_index.num_levels(), gpjson::test::index::kMaxDepth);
  ASSERT_EQ(leveled_bitmap_index.size_bytes(), expected.size() * sizeof(long));
  EXPECT_EQ(gpjson::test::index::copy_index_words(leveled_bitmap_index),
            expected);
}

TEST(ExpectedIndexTest, ComputesExpectedLeveledBitmapIndex) {
  const std::string data = "{\"a\":[1,2]}";
  const std::vector<long> oracle{
      gpjson::test::index::word_from_bits(0b10000010001),
      gpjson::test::index::word_from_bits(0b1010100000),
      gpjson::test::index::word_from_bits(0)};

  EXPECT_EQ(expected_leveled_bitmap_index(data, 3), oracle);
}

INSTANTIATE_TEST_SUITE_P(
    AllIndexBuilders, LeveledBitmapIndexBuilderTest,
    ::testing::ValuesIn(gpjson::test::index::kIndexBuilderTypes),
    gpjson::test::index::index_builder_type_test_name);

} // namespace
