/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agent) against the codebase with
 * human review and feedback
 */

#include "index/index_test_utils.hpp"
#include "utils/utils.hpp"

#include "gpjson/cuda/cuda.hpp"
#include "gpjson/file/file_reader.hpp"
#include "gpjson/index/index_builder.hpp"

#include <gtest/gtest.h>

#include <cstddef>
#include <string>
#include <vector>

namespace {

class NewlineIndexBuilderTest
    : public ::testing::TestWithParam<gpjson::index::IndexBuilderType> {};

std::vector<long> expected_newline_index(const std::string &data) {
  std::vector<long> newline_index{0};
  for (size_t i = 0; i < data.size(); ++i) {
    if (data[i] == '\n') {
      newline_index.push_back(static_cast<long>(i));
    }
  }
  return newline_index;
}

TEST_P(NewlineIndexBuilderTest, BuildsNewlineIndex) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::test::index::StaticPartition partition(
      gpjson::test::index::ld_json_fixture());
  partition.load_to_device();
  gpjson::file::CopiedFileReader file_reader{"in-memory.ldjson"};
  const gpjson::index::IndexBuilderType builder_type = GetParam();
  auto builder =
      gpjson::test::index::make_index_builder(builder_type, file_reader);

  gpjson::index::BuiltIndices indices =
      builder->build(partition.view(), gpjson::test::index::kMaxDepth,
                     gpjson::test::index::small_builder_options(builder_type));
  gpjson::cuda::synchronize_and_check();

  const std::vector<long> expected = expected_newline_index(partition.data());
  const gpjson::index::NewlineIndex &newline_index =
      indices.get_newline_index();

  EXPECT_EQ(newline_index.num_lines(), static_cast<int>(expected.size()));
  ASSERT_EQ(newline_index.size_bytes(), expected.size() * sizeof(long));
  EXPECT_EQ(gpjson::test::index::copy_index_words(newline_index), expected);
}

TEST(ExpectedIndexTest, ComputesExpectedNewlineIndex) {
  const std::string data = "first\nsecond\nthird";
  const std::vector<long> oracle{0, 5, 12};

  EXPECT_EQ(expected_newline_index(data), oracle);
}

INSTANTIATE_TEST_SUITE_P(
    AllIndexBuilders, NewlineIndexBuilderTest,
    ::testing::ValuesIn(gpjson::test::index::kIndexBuilderTypes),
    gpjson::test::index::index_builder_type_test_name);

} // namespace
