/*
 * Disclaimer: All test cases are generated by codex against the codebase
 */

#include "index/index_test_utils.hpp"
#include "utils/utils.hpp"

#include "gpjson/cuda/cuda.hpp"
#include "gpjson/file/file_reader.hpp"
#include "gpjson/index/index_builder.hpp"

#include <gtest/gtest.h>

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>
#include <vector>

namespace {

long word_from_bits(uint64_t bits) {
  long word = 0;
  static_assert(sizeof(word) == sizeof(bits));
  std::memcpy(&word, &bits, sizeof(word));
  return word;
}

uint64_t bit_for(size_t offset) { return uint64_t{1} << (offset % 64); }

size_t level_size_for(size_t file_size) { return (file_size + 64 - 1) / 64; }

bool is_escaped_quote(const std::string &data, size_t quote_offset) {
  size_t slash_count = 0;
  for (size_t i = quote_offset; i > 0 && data[i - 1] == '\\'; --i) {
    ++slash_count;
  }
  return slash_count % 2 == 1;
}

std::vector<long> expected_string_index(const std::string &data) {
  std::vector<uint64_t> words(level_size_for(data.size()), 0);
  bool in_string = false;

  for (size_t i = 0; i < data.size(); ++i) {
    if (data[i] == '"' && !is_escaped_quote(data, i)) {
      if (!in_string) {
        words[i / 64] |= bit_for(i);
        in_string = true;
      } else {
        in_string = false;
      }
    } else if (in_string) {
      words[i / 64] |= bit_for(i);
    }
  }

  std::vector<long> expected;
  for (uint64_t word : words) {
    expected.push_back(word_from_bits(word));
  }
  return expected;
}

TEST(IndexBuilderTest, BuildsStringIndex) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  gpjson::test::index::StaticPartition partition(
      gpjson::test::index::ld_json_fixture());
  gpjson::file::FileReader file_reader{"in-memory.ldjson"};
  gpjson::index::UncombinedIndexBuilder builder{file_reader};

  gpjson::index::BuiltIndices indices =
      builder.build(partition.view(), gpjson::test::index::kMaxDepth,
                    gpjson::test::index::small_builder_options());
  gpjson::cuda::synchronize();

  const std::vector<long> expected = expected_string_index(partition.data());
  const gpjson::index::StringIndex &string_index = indices.get_string_index();

  ASSERT_EQ(string_index.size_bytes(), expected.size() * sizeof(long));
  EXPECT_EQ(gpjson::test::index::copy_index_words(string_index), expected);
}

} // namespace
