/*
 * Disclaimer: All test cases are generated by codex against the codebase
 */

#include <cstddef>
#include <memory>
#include <string>
#include <utility>
#include <vector>

#include "gpjson/cuda/cuda.hpp"
#include "utils/utils.hpp"

#define private public
#include "gpjson/file/file.hpp"
#undef private

#include "gpjson/file/file_reader.hpp"
#include "gpjson/index/index.hpp"
#include "gpjson/index/index_builder.hpp"

#include <cuda_runtime_api.h>
#include <gtest/gtest.h>

namespace {

constexpr int kMaxDepth = 8;

/* Create a PartitionView from a cpp string */
class StaticPartition {
public:
  explicit StaticPartition(std::string data) : data_(std::move(data)) {
    view_.partition_id_ = 0;
    view_.global_start_offset_ = 0;
    view_.global_end_offset_ = data_.size();
    view_.data_ = reinterpret_cast<const std::byte *>(data_.data());
  }

  const gpjson::file::PartitionView &view() const { return view_; }

  const std::string &data() const { return data_; }

private:
  std::string data_;
  gpjson::file::PartitionView view_;
};

std::string ld_json_fixture() {
  return std::string{
      "{\"id\":1,\"name\":\"Ada\",\"tags\":[\"gpu\",\"json\"],\"active\":true}"
      "\n"
      "{\"id\":2,\"name\":\"Bob \\\"The Builder\\\"\","
      "\"note\":\"literal { braces } and [brackets] stay strings\"}"
      "\n"
      "{\"id\":3,\"nested\":{\"arr\":[1,{\"x\":\"y,z\"}],\"empty\":{}},"
      "\"path\":\"C:\\\\tmp\\\\file\"}"};
}

std::vector<long> expected_newline_index(const std::string &data) {
  std::vector<long> newline_index{0};
  for (size_t i = 0; i < data.size(); ++i) {
    if (data[i] == '\n') {
      newline_index.push_back(static_cast<long>(i));
    }
  }
  return newline_index;
}

std::vector<long> copy_index_words(const gpjson::index::Index &index) {
  std::vector<long> words(index.size_bytes() / sizeof(long), 0);
  if (index.size_bytes() > 0) {
    gpjson::cuda::check(cudaMemcpy(words.data(), index.data(),
                                   index.size_bytes(), cudaMemcpyDeviceToHost),
                        "cudaMemcpy index to host");
  }
  return words;
}

gpjson::index::IndexBuilderOptions small_builder_options() {
  return gpjson::index::IndexBuilderOptions{
      gpjson::index::IndexBuilderType::UNCOMBINED, 0, 1, 64, 1, 64,
  };
}

TEST(IndexBuilderTest, BuildsNewlineIndex) {
  GPJSON_SKIP_IF_CUDA_UNAVAILABLE();

  StaticPartition partition(ld_json_fixture());
  gpjson::file::FileReader file_reader{"in-memory.ldjson"};
  gpjson::index::UncombinedIndexBuilder builder{file_reader};

  gpjson::index::BuiltIndices indices =
      builder.build(partition.view(), kMaxDepth, small_builder_options());
  gpjson::cuda::synchronize();

  const std::vector<long> expected = expected_newline_index(partition.data());
  const gpjson::index::NewlineIndex &newline_index =
      indices.get_newline_index();

  EXPECT_EQ(newline_index.num_lines(), static_cast<int>(expected.size()));
  ASSERT_EQ(newline_index.size_bytes(), expected.size() * sizeof(long));
  EXPECT_EQ(copy_index_words(newline_index), expected);
}

} // namespace
