/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#pragma once

#include <chrono>
#include <cstdarg>
#include <cstddef>
#include <string>
#include <string_view>
#include <vector>

namespace gpjson::profiler {

class Profiler {
public:
  explicit Profiler(std::string name = "Profiler");

  class SegmentId {
  public:
    SegmentId() = default;

  private:
    explicit SegmentId(size_t index);

    size_t index_{0};
    bool valid_{false};

    friend class Profiler;
  };

  SegmentId begin(std::string_view name);
  SegmentId beginf(const char *fmt, ...);

  void end(SegmentId segment_id);
  void indent();
  void unindent();

private:
  using Clock = std::chrono::steady_clock;
  using Duration = std::chrono::nanoseconds;
  using TimePoint = Clock::time_point;

  struct SegmentRecord {
    std::string name;
    TimePoint start_time{};
    Duration elapsed{Duration::zero()};
    size_t indent_level{0};
    bool completed{false};
  };

  SegmentId begin_formatted(const char *fmt, va_list args);
  std::string vformat(const char *fmt, va_list args) const;

  std::string name_;
  std::vector<SegmentRecord> segments_;
  size_t indent_level_{0};
};
} // namespace gpjson::profiler
