/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agent) against the codebase with
 * human review and feedback
 */

#pragma once

#include "gpjson/file/file_reader.hpp"

#include <gtest/gtest.h>

#include <array>
#include <memory>
#include <stdexcept>
#include <string>

namespace gpjson::test::file {

inline constexpr std::array<gpjson::file::FileReaderType, 2> kFileReaderTypes{
    gpjson::file::FileReaderType::COPIED,
    gpjson::file::FileReaderType::MMAP,
};

inline const char *
file_reader_type_name(gpjson::file::FileReaderType file_reader_type) {
  switch (file_reader_type) {
  case gpjson::file::FileReaderType::COPIED:
    return "COPIED";
  case gpjson::file::FileReaderType::MMAP:
    return "MMAP";
  }

  throw std::invalid_argument("Unknown file reader type.");
}

inline std::string file_reader_type_test_name(
    const ::testing::TestParamInfo<gpjson::file::FileReaderType> &info) {
  return file_reader_type_name(info.param);
}

inline std::unique_ptr<gpjson::file::FileReader>
make_file_reader(gpjson::file::FileReaderType file_reader_type,
                 const std::string &file_path) {
  switch (file_reader_type) {
  case gpjson::file::FileReaderType::COPIED:
    return std::make_unique<gpjson::file::CopiedFileReader>(file_path);
  case gpjson::file::FileReaderType::MMAP:
    return std::make_unique<gpjson::file::MmapFileReader>(file_path);
  }

  throw std::invalid_argument("Unknown file reader type.");
}

} // namespace gpjson::test::file
