/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "driver_config.hpp"

#include <gtest/gtest.h>

#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

std::vector<char *> argv_from(std::vector<std::string> &args) {
  std::vector<char *> argv;
  argv.reserve(args.size());
  for (std::string &arg : args) {
    argv.push_back(arg.data());
  }
  return argv;
}

std::filesystem::path write_temp_config(const std::string &contents) {
  const auto now = std::chrono::steady_clock::now().time_since_epoch().count();
  const std::filesystem::path path =
      std::filesystem::temp_directory_path() /
      ("gpjson_driver_config_test_" + std::to_string(now) + ".toml");

  std::ofstream output(path);
  output << contents;
  return path;
}

gpjson::driver::DriverInputs parse_args(std::vector<std::string> args) {
  std::vector<char *> argv = argv_from(args);
  return gpjson::driver::parse_driver_inputs(static_cast<int>(argv.size()),
                                             argv.data());
}

} // namespace

TEST(DriverConfigTest, DefaultInputsUseOptionStructDefaults) {
  const gpjson::driver::DriverInputs inputs =
      gpjson::driver::default_driver_inputs();

  EXPECT_TRUE(inputs.dataset_path.empty());
  EXPECT_TRUE(inputs.queries.empty());
  const auto &index_options = inputs.engine_options.index_builder_options;
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::UNCOMBINED);
  EXPECT_EQ(index_options.file_partition_size, 0U);
  EXPECT_EQ(index_options.grid_size, 0);
  EXPECT_EQ(index_options.block_size, 0);
  EXPECT_EQ(index_options.reduction_grid_size, 0);
  EXPECT_EQ(index_options.reduction_block_size, 0);
}

TEST(DriverConfigTest, ParsesTomlConfig) {
  const std::filesystem::path config_path = write_temp_config(R"toml(
dataset_path = "dataset/input.json"
queries = ["$.user.lang", "$.user.id"]

[index_builder]
type = "COMBINED"
file_partition_size = 65536
grid_size = 16384
block_size = 1024
reduction_grid_size = 32
reduction_block_size = 16
)toml");

  const gpjson::driver::DriverInputs inputs =
      parse_args({"gpjson_driver", "--config", config_path.string()});

  EXPECT_EQ(inputs.dataset_path, "dataset/input.json");
  ASSERT_EQ(inputs.queries.size(), 2U);
  EXPECT_EQ(inputs.queries[0], "$.user.lang");
  EXPECT_EQ(inputs.queries[1], "$.user.id");

  const auto &index_options = inputs.engine_options.index_builder_options;
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(index_options.file_partition_size, 65536U);
  EXPECT_EQ(index_options.grid_size, 16384);
  EXPECT_EQ(index_options.block_size, 1024);
  EXPECT_EQ(index_options.reduction_grid_size, 32);
  EXPECT_EQ(index_options.reduction_block_size, 16);

  std::filesystem::remove(config_path);
}

TEST(DriverConfigTest, CliOverridesTomlConfig) {
  const std::filesystem::path config_path = write_temp_config(R"toml(
dataset_path = "dataset/from_toml.json"
queries = ["$.toml"]

[index_builder]
type = "UNCOMBINED"
grid_size = 1
block_size = 2
)toml");

  const gpjson::driver::DriverInputs inputs =
      parse_args({"gpjson_driver", "--config", config_path.string(),
                  "--dataset", "dataset/from_cli.json", "--query", "$.cli.one",
                  "--query", "$.cli.two", "--index-builder.type", "COMBINED",
                  "--index-builder.grid-size", "16384"});

  EXPECT_EQ(inputs.dataset_path, "dataset/from_cli.json");
  ASSERT_EQ(inputs.queries.size(), 2U);
  EXPECT_EQ(inputs.queries[0], "$.cli.one");
  EXPECT_EQ(inputs.queries[1], "$.cli.two");

  const auto &index_options = inputs.engine_options.index_builder_options;
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(index_options.grid_size, 16384);
  EXPECT_EQ(index_options.block_size, 2);

  std::filesystem::remove(config_path);
}

TEST(DriverConfigTest, ParsesEnumAliases) {
  EXPECT_EQ(gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
                "COMBINED"),
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
                "FUSED"),
            gpjson::index::IndexBuilderType::FUSED);
}

TEST(DriverConfigTest, RejectsInvalidEnum) {
  EXPECT_THROW(
      gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
          "BAD_BUILDER"),
      std::runtime_error);
}
