/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agent) against the codebase with
 * human review and feedback
 */

#include "driver_config.hpp"

#include <gtest/gtest.h>

#include <chrono>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace {

std::vector<char *> argv_from(std::vector<std::string> &args) {
  std::vector<char *> argv;
  argv.reserve(args.size());
  for (std::string &arg : args) {
    argv.push_back(arg.data());
  }
  return argv;
}

std::filesystem::path write_temp_config(const std::string &contents) {
  const auto now = std::chrono::steady_clock::now().time_since_epoch().count();
  const std::filesystem::path path =
      std::filesystem::temp_directory_path() /
      ("gpjson_driver_config_test_" + std::to_string(now) + ".toml");

  std::ofstream output(path);
  output << contents;
  return path;
}

gpjson::driver::DriverInputs parse_args(std::vector<std::string> args) {
  std::vector<char *> argv = argv_from(args);
  return gpjson::driver::parse_driver_inputs(static_cast<int>(argv.size()),
                                             argv.data());
}

} // namespace

TEST(DriverConfigTest, DefaultInputsUseOptionStructDefaults) {
  const gpjson::driver::DriverInputs inputs =
      gpjson::driver::default_driver_inputs();

  EXPECT_FALSE(inputs.run_name.empty());
  EXPECT_TRUE(inputs.dataset_path.empty());
  EXPECT_TRUE(inputs.queries.empty());
  const auto &file_reader_options = inputs.engine_options.file_reader_options;
  const auto &index_options = inputs.engine_options.index_builder_options;
  const auto &query_options = inputs.engine_options.query_executor_options;
  EXPECT_EQ(file_reader_options.file_reader_type,
            gpjson::file::FileReaderType::COPIED);
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::UNCOMBINED);
  EXPECT_EQ(index_options.file_partition_size, 0U);
  EXPECT_EQ(index_options.grid_size, 0);
  EXPECT_EQ(index_options.block_size, 0);
  EXPECT_EQ(index_options.reduction_grid_size, 0);
  EXPECT_EQ(index_options.reduction_block_size, 0);
  EXPECT_EQ(query_options.grid_size, 512);
  EXPECT_EQ(query_options.block_size, 1024);
}

TEST(DriverConfigTest, ParsesTomlConfig) {
  const std::filesystem::path config_path = write_temp_config(R"toml(
dataset_path = "dataset/input.json"
run_name = "toml_run"
queries = ["$.user.lang", "$.user.id"]

[file_reader]
type = "MMAP"

[index_builder]
type = "COMBINED"
file_partition_size = 65536
grid_size = 16384
block_size = 1024
reduction_grid_size = 32
reduction_block_size = 16

[query_executor]
grid_size = 99
block_size = 128
)toml");

  const gpjson::driver::DriverInputs inputs =
      parse_args({"gpjson_driver", "--config", config_path.string()});

  EXPECT_EQ(inputs.run_name, "toml_run");
  EXPECT_EQ(inputs.dataset_path, "dataset/input.json");
  ASSERT_EQ(inputs.queries.size(), 2U);
  EXPECT_EQ(inputs.queries[0], "$.user.lang");
  EXPECT_EQ(inputs.queries[1], "$.user.id");

  const auto &file_reader_options = inputs.engine_options.file_reader_options;
  const auto &index_options = inputs.engine_options.index_builder_options;
  const auto &query_options = inputs.engine_options.query_executor_options;
  EXPECT_EQ(file_reader_options.file_reader_type,
            gpjson::file::FileReaderType::MMAP);
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(index_options.file_partition_size, 65536U);
  EXPECT_EQ(index_options.grid_size, 16384);
  EXPECT_EQ(index_options.block_size, 1024);
  EXPECT_EQ(index_options.reduction_grid_size, 32);
  EXPECT_EQ(index_options.reduction_block_size, 16);
  EXPECT_EQ(query_options.grid_size, 99);
  EXPECT_EQ(query_options.block_size, 128);

  std::filesystem::remove(config_path);
}

TEST(DriverConfigTest, CliOverridesTomlConfig) {
  const std::filesystem::path config_path = write_temp_config(R"toml(
dataset_path = "dataset/from_toml.json"
run_name = "toml_run"
queries = ["$.toml"]

[file_reader]
type = "COPIED"

[index_builder]
type = "UNCOMBINED"
grid_size = 1
block_size = 2

[query_executor]
grid_size = 3
block_size = 4
)toml");

  const gpjson::driver::DriverInputs inputs =
      parse_args({"gpjson_driver",
                  "--config",
                  config_path.string(),
                  "--dataset",
                  "dataset/from_cli.json",
                  "--query",
                  "$.cli.one",
                  "--query",
                  "$.cli.two",
                  "--run-name",
                  "cli_run",
                  "--index-builder.type",
                  "COMBINED",
                  "--file-reader.type",
                  "MMAP",
                  "--index-builder.grid-size",
                  "16384",
                  "--query-executor.grid-size",
                  "55",
                  "--query-executor.block-size",
                  "64"});

  EXPECT_EQ(inputs.run_name, "cli_run");
  EXPECT_EQ(inputs.dataset_path, "dataset/from_cli.json");
  ASSERT_EQ(inputs.queries.size(), 2U);
  EXPECT_EQ(inputs.queries[0], "$.cli.one");
  EXPECT_EQ(inputs.queries[1], "$.cli.two");

  const auto &file_reader_options = inputs.engine_options.file_reader_options;
  const auto &index_options = inputs.engine_options.index_builder_options;
  const auto &query_options = inputs.engine_options.query_executor_options;
  EXPECT_EQ(file_reader_options.file_reader_type,
            gpjson::file::FileReaderType::MMAP);
  EXPECT_EQ(index_options.index_builder_type,
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(index_options.grid_size, 16384);
  EXPECT_EQ(index_options.block_size, 2);
  EXPECT_EQ(query_options.grid_size, 55);
  EXPECT_EQ(query_options.block_size, 64);

  std::filesystem::remove(config_path);
}

TEST(DriverConfigTest, RejectsNegativeQueryExecutorLaunchSizes) {
  gpjson::driver::DriverInputs inputs = gpjson::driver::default_driver_inputs();
  inputs.dataset_path = "dataset/input.json";
  inputs.queries = {"$.user.lang"};
  inputs.engine_options.query_executor_options.grid_size = -1;

  EXPECT_THROW(gpjson::driver::validate_driver_inputs(inputs),
               std::runtime_error);
}

TEST(DriverConfigTest, ParsesEnumAliases) {
  EXPECT_EQ(
      gpjson::driver::parse_enum_value<gpjson::file::FileReaderType>("COPIED"),
      gpjson::file::FileReaderType::COPIED);
  EXPECT_EQ(
      gpjson::driver::parse_enum_value<gpjson::file::FileReaderType>("MMAP"),
      gpjson::file::FileReaderType::MMAP);
  EXPECT_EQ(gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
                "COMBINED"),
            gpjson::index::IndexBuilderType::COMBINED);
  EXPECT_EQ(gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
                "FUSED"),
            gpjson::index::IndexBuilderType::FUSED);
}

TEST(DriverConfigTest, RejectsInvalidEnum) {
  EXPECT_THROW(gpjson::driver::parse_enum_value<gpjson::file::FileReaderType>(
                   "BAD_READER"),
               std::runtime_error);
  EXPECT_THROW(
      gpjson::driver::parse_enum_value<gpjson::index::IndexBuilderType>(
          "BAD_BUILDER"),
      std::runtime_error);
}
