/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "gpjson/profiler/profiler.hpp"

#include "gpjson/log/log.hpp"

#include <cstdarg>
#include <cstdio>
#include <utility>
#include <vector>

namespace gpjson::profiler {

namespace {

constexpr double kNanosecondsPerMillisecond = 1000000.0;
constexpr size_t kSpacesPerIndent = 2;

} // namespace

Profiler::Profiler(std::string name) : name_(std::move(name)) {}

Profiler::SegmentId::SegmentId(size_t index) : index_(index), valid_(true) {}

Profiler::SegmentId Profiler::begin(std::string_view name) {
  SegmentRecord record;
  record.name = std::string(name);
  record.start_time = Clock::now();
  record.indent_level = indent_level_;
  segments_.push_back(std::move(record));
  return SegmentId(segments_.size() - 1);
}

Profiler::SegmentId Profiler::beginf(const char *fmt, ...) {
  va_list args;
  va_start(args, fmt);
  const SegmentId segment_id = begin_formatted(fmt, args);
  va_end(args);
  return segment_id;
}

Profiler::SegmentId Profiler::begin_formatted(const char *fmt, va_list args) {
  return begin(vformat(fmt, args));
}

void Profiler::end(SegmentId segment_id) {
  Assert(segment_id.valid_, "Profiler end called with invalid segment id.");
  if (!segment_id.valid_) {
    return;
  }

  Assert(segment_id.index_ < segments_.size(),
         "Profiler end segment id %zu out of bounds.", segment_id.index_);
  if (segment_id.index_ >= segments_.size()) {
    return;
  }

  SegmentRecord &record = segments_[segment_id.index_];
  Assert(!record.completed, "Profiler segment '%s' already completed.",
         record.name.c_str());
  if (record.completed) {
    return;
  }

  record.elapsed =
      std::chrono::duration_cast<Duration>(Clock::now() - record.start_time);
  record.completed = true;

  const double elapsed_ms =
      static_cast<double>(record.elapsed.count()) / kNanosecondsPerMillisecond;
  const int indent_width =
      static_cast<int>(record.indent_level * kSpacesPerIndent);
  std::fprintf(stdout, "%s: %*s%s: %.3f ms\n", name_.c_str(), indent_width, "",
               record.name.c_str(), elapsed_ms);
  std::fflush(stdout);
}

void Profiler::indent() { ++indent_level_; }

void Profiler::unindent() {
  Assert(indent_level_ > 0, "Profiler unindent called at indent level 0.");
  if (indent_level_ == 0) {
    return;
  }
  --indent_level_;
}

std::string Profiler::vformat(const char *fmt, va_list args) const {
  va_list copied_args;
  va_copy(copied_args, args);
  const int size = std::vsnprintf(nullptr, 0, fmt, copied_args);
  va_end(copied_args);

  Assert(size >= 0, "Failed to format profiler segment name.");
  if (size < 0) {
    return {};
  }

  std::vector<char> buffer(static_cast<size_t>(size) + 1, '\0');
  va_copy(copied_args, args);
  std::vsnprintf(buffer.data(), buffer.size(), fmt, copied_args);
  va_end(copied_args);

  return std::string(buffer.data(), static_cast<size_t>(size));
}

} // namespace gpjson::profiler
