/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "driver_config.hpp"

#include <CLI/CLI.hpp>
#include <toml++/toml.hpp>

#include <cctype>
#include <cstddef>
#include <cstdint>
#include <initializer_list>
#include <limits>
#include <memory>
#include <ostream>
#include <stdexcept>
#include <string_view>
#include <type_traits>
#include <utility>

namespace gpjson::driver {
namespace {

std::string to_cli_key(std::string_view key) {
  std::string cli_key;
  cli_key.reserve(key.size());
  for (const char c : key) {
    cli_key.push_back(c == '_' ? '-' : c);
  }
  return cli_key;
}

std::string to_cli_option_name(std::string_view key) {
  if (key.size() == 1) {
    return "-" + std::string(key);
  }
  return "--" + to_cli_key(key);
}

std::string option_names(std::string_view key,
                         std::initializer_list<std::string_view> aliases = {}) {
  std::string names = to_cli_option_name(key);
  for (std::string_view alias : aliases) {
    names += ",";
    names += to_cli_option_name(alias);
  }
  return names;
}

template <class T>
T checked_integral_cast(const std::int64_t value, std::string_view key) {
  if constexpr (std::is_unsigned_v<T>) {
    if (value < 0) {
      throw std::runtime_error("TOML value for '" + std::string(key) +
                               "' must be non-negative.");
    }
    if (static_cast<std::uint64_t>(value) >
        static_cast<std::uint64_t>(std::numeric_limits<T>::max())) {
      throw std::runtime_error("TOML value for '" + std::string(key) +
                               "' is out of range.");
    }
  } else {
    if (value < static_cast<std::int64_t>(std::numeric_limits<T>::lowest()) ||
        value > static_cast<std::int64_t>(std::numeric_limits<T>::max())) {
      throw std::runtime_error("TOML value for '" + std::string(key) +
                               "' is out of range.");
    }
  }
  return static_cast<T>(value);
}

class TomlBinder {
public:
  explicit TomlBinder(const toml::table &table) : table_(table) {}

  template <class T>
  void value(std::string_view key, T &field,
             std::initializer_list<std::string_view> = {}) const {
    const toml::node_view<const toml::node> node =
        table_.at_path(std::string(key));
    if (!node) {
      return;
    }

    if constexpr (std::is_integral_v<T>) {
      const auto value = node.value<std::int64_t>();
      if (!value.has_value()) {
        throw std::runtime_error("TOML value for '" + std::string(key) +
                                 "' must be an integer.");
      }
      field = checked_integral_cast<T>(*value, key);
    } else {
      const auto value = node.value<T>();
      if (!value.has_value()) {
        throw std::runtime_error("TOML value for '" + std::string(key) +
                                 "' has the wrong type.");
      }
      field = *value;
    }
  }

  void list(std::string_view key, std::vector<std::string> &field,
            std::initializer_list<std::string_view> = {}) const {
    const toml::node_view<const toml::node> node =
        table_.at_path(std::string(key));
    if (!node) {
      return;
    }

    const toml::array *array = node.as_array();
    if (array == nullptr) {
      throw std::runtime_error("TOML value for '" + std::string(key) +
                               "' must be an array of strings.");
    }

    std::vector<std::string> values;
    values.reserve(array->size());
    for (const toml::node &entry : *array) {
      const auto value = entry.value<std::string>();
      if (!value.has_value()) {
        throw std::runtime_error("TOML array '" + std::string(key) +
                                 "' must contain only strings.");
      }
      values.push_back(*value);
    }
    field = std::move(values);
  }

  template <class Enum>
  void enum_value(std::string_view key, Enum &field,
                  std::initializer_list<std::string_view> = {}) const {
    std::string value;
    this->value(key, value);
    if (!value.empty()) {
      field = parse_enum_value<Enum>(value);
    }
  }

private:
  const toml::table &table_;
};

class CliBinder {
public:
  explicit CliBinder(CLI::App &app) : app_(app) {}

  template <class T>
  void value(std::string_view key, T &field,
             std::initializer_list<std::string_view> aliases = {}) {
    app_.add_option(option_names(key, aliases), field);
  }

  void list(std::string_view key, std::vector<std::string> &field,
            std::initializer_list<std::string_view> aliases = {}) {
    auto binding = std::make_unique<StringListBinding>();
    binding->target = &field;
    binding->option =
        app_.add_option(option_names(key, aliases), binding->parsed);
    string_lists_.push_back(std::move(binding));
  }

  template <class Enum>
  void enum_value(std::string_view key, Enum &field,
                  std::initializer_list<std::string_view> aliases = {}) {
    app_.add_option_function<std::string>(
        option_names(key, aliases), [&field](const std::string &text) {
          field = parse_enum_value<Enum>(text);
        });
  }

  void finalize() {
    for (const auto &binding : string_lists_) {
      if (binding->option->count() > 0) {
        *binding->target = binding->parsed;
      }
    }
  }

private:
  struct StringListBinding {
    std::vector<std::string> parsed;
    std::vector<std::string> *target{nullptr};
    CLI::Option *option{nullptr};
  };

  CLI::App &app_;
  std::vector<std::unique_ptr<StringListBinding>> string_lists_;
};

template <class Binder>
void bind_file_reader_options(Binder &binder,
                              gpjson::file::FileReaderOptions &options) {
  binder.enum_value("file_reader.type", options.file_reader_type);
}

template <class Binder>
void bind_index_builder_options(Binder &binder,
                                gpjson::index::IndexBuilderOptions &options) {
  binder.enum_value("index_builder.type", options.index_builder_type);
  binder.value("index_builder.file_partition_size",
               options.file_partition_size);
  binder.value("index_builder.grid_size", options.grid_size);
  binder.value("index_builder.block_size", options.block_size);
  binder.value("index_builder.reduction_grid_size",
               options.reduction_grid_size);
  binder.value("index_builder.reduction_block_size",
               options.reduction_block_size);
}

template <class Binder>
void bind_driver_inputs(Binder &binder, DriverInputs &inputs) {
  binder.value("dataset_path", inputs.dataset_path, {"dataset"});
  binder.list("queries", inputs.queries, {"query", "q"});
  bind_file_reader_options(binder, inputs.engine_options.file_reader_options);
  bind_index_builder_options(binder,
                             inputs.engine_options.index_builder_options);
}

std::optional<std::filesystem::path> parse_config_path(int argc, char **argv) {
  std::string config_path;
  CLI::App app{"gpjson driver config pre-parser"};
  app.allow_extras();
  app.set_help_flag("", "");
  app.add_option("-c,--config", config_path, "TOML config file path");
  app.parse(argc, argv);
  if (config_path.empty()) {
    return std::nullopt;
  }
  return std::filesystem::path(config_path);
}

} // namespace

CliExit::CliExit(const int exit_code) : exit_code_(exit_code) {}

const char *CliExit::what() const noexcept { return "CLI requested exit"; }

int CliExit::exit_code() const noexcept { return exit_code_; }

DriverInputs default_driver_inputs() { return DriverInputs{}; }

DriverInputs parse_driver_inputs(int argc, char **argv) {
  std::optional<std::filesystem::path> config_path =
      parse_config_path(argc, argv);

  DriverInputs inputs = default_driver_inputs();

  if (config_path.has_value()) {
    const toml::table table = toml::parse_file(config_path->string());
    TomlBinder toml_binder(table);
    bind_driver_inputs(toml_binder, inputs);
  }

  CLI::App app{"Run gpjson queries against a JSON-lines dataset"};
  std::string config_path_arg =
      config_path.has_value() ? config_path->string() : "";
  app.add_option("-c,--config", config_path_arg, "TOML config file path");
  CliBinder cli_binder(app);
  bind_driver_inputs(cli_binder, inputs);
  try {
    app.parse(argc, argv);
  } catch (const CLI::ParseError &error) {
    throw CliExit(app.exit(error));
  }
  cli_binder.finalize();

  validate_driver_inputs(inputs);
  return inputs;
}

void validate_driver_inputs(const DriverInputs &inputs) {
  if (inputs.dataset_path.empty()) {
    throw std::runtime_error("dataset_path is required. Use --dataset or set "
                             "dataset_path in the TOML config.");
  }

  if (inputs.queries.empty()) {
    throw std::runtime_error("At least one query is required. Use --query or "
                             "set queries in the TOML config.");
  }

  const auto &options = inputs.engine_options.index_builder_options;

  if (options.grid_size < 0 || options.block_size < 0 ||
      options.reduction_grid_size < 0 || options.reduction_block_size < 0) {
    throw std::runtime_error(
        "Index builder grid and block sizes must be non-negative.");
  }
}

} // namespace gpjson::driver
