/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#pragma once

#include "gpjson/engine.hpp"

#include <exception>
#include <iosfwd>
#include <magic_enum/magic_enum.hpp>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace gpjson::driver {

struct DriverInputs {
  std::string dataset_path;
  std::vector<std::string> queries;
  gpjson::EngineOptions engine_options;
};

class CliExit final : public std::exception {
public:
  explicit CliExit(int exit_code);

  const char *what() const noexcept override;
  int exit_code() const noexcept;

private:
  int exit_code_;
};

DriverInputs default_driver_inputs();

DriverInputs parse_driver_inputs(int argc, char **argv);

void validate_driver_inputs(const DriverInputs &inputs);

template <class Enum> Enum parse_enum_value(const std::string &text) {
  const auto value = magic_enum::enum_cast<Enum>(text);
  if (!value.has_value()) {
    std::ostringstream message;
    message << "Invalid enum value '" << text << "'. Expected one of:";
    bool first = true;
    for (const auto enum_name : magic_enum::enum_names<Enum>()) {
      message << (first ? " " : ", ") << enum_name;
      first = false;
    }
    throw std::runtime_error(message.str());
  }
  return *value;
}

} // namespace gpjson::driver
