/*
 * AI Disclaimer:
 *
 * This file is generated by codex (AI coding agnet) against the codebase with
 * human review and feedback
 */

#include "driver_config.hpp"

#include "gpjson/engine.hpp"
#include "gpjson/query/query.hpp"

#include <exception>
#include <iostream>

void summarize_result(const gpjson::query::MaterializedBatchResult &result) {
  std::cout << "Result has " << result.queries().size() << " queries" << "\n";
  for (const auto &query : result.queries()) {
    std::cout << "Query '" << query.query_text() << "' has "
              << query.lines().size() << " lines of result, ";
    unsigned long num_matches = 0;
    for (const auto &line : query.lines()) {
      num_matches += line.values().size();
    }
    std::cout << "and " << num_matches << " matched values";
    std::cout << "\n";
  }
}

int main(int argc, char **argv) {
  try {
    const gpjson::driver::DriverInputs inputs =
        gpjson::driver::parse_driver_inputs(argc, argv);

    gpjson::Engine engine{};
    const gpjson::query::MaterializedBatchResult result = engine.query(
        inputs.dataset_path, inputs.queries, inputs.engine_options);
    summarize_result(result);

    return 0;
  } catch (const gpjson::driver::CliExit &exit) {
    return exit.exit_code();
  } catch (const std::exception &error) {
    std::cerr << "gpjson_driver: " << error.what() << '\n';
    return 1;
  }
}
