dataset_path = "dataset/twitter_small_records_remove.json"
queries = ["$.user.lang"]

[file_reader]
type = "MMAP"

[index_builder]
type = "COMBINED"
grid_size = 16384
block_size = 1024
reduction_grid_size = 32
reduction_block_size = 32

[query_executor]
grid_size = 512
block_size = 1024
